notifications:
  email:
    on_success: never
language: cpp
sudo: false
os:
  - osx
  - linux
addons:
  apt:
    packages:
    - cmake
    - ninja-build
env:
  global:
    - NINJA_STATUS="[%p %u/%t@%o %r]"
    - PROJECT_NAME=${PWD##*/}
  matrix:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (brew outdated cmake || brew upgrade cmake); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja; fi

script:
  - mkdir $BUILD_TYPE
  - cd $BUILD_TYPE
  - cmake -GNinja -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - ninja
